# Sample configuration for Telco Customer Churn columns
# Adjust to match your CSV header exactly (case-sensitive)

target: Churn

numeric:
  - tenure
  - MonthlyCharges
  - TotalCharges

categorical:
  - gender
  - SeniorCitizen
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod
